# roles/nginx/tasks/main.yml
---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create directory for static content
  file:
    path: /var/www/html/hello-world
    state: directory
    mode: 0755

- name: Create "index.html" file with "hello world" content
  template:
    src: "index.html.j2"
    dest: /var/www/html/hello-world/index.html
    mode: 0644

- name: Copy "index.html" to default Nginx location
  copy:
    src: /var/www/html/hello-world/index.html
    dest: /var/www/html/index.html
    mode: 0644
    remote_src: true

- name: Enable default Nginx website
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Permission to nginx log directory
  ansible.builtin.file:
    path: /var/log/nginx
    state: directory
    recurse: yes
    mode: '0777'
  become: true

- name: Deploy logrotate configuration for nginx access log
  template:
    src: templates/logrotate.conf
    dest: /etc/logrotate.d/nginx-access
    mode: '0644'
  become: yes

- name: Restart nginx service
  service:
    name: nginx
    state: restarted
  become: yes

- name: Configure UFW
  ufw:
    rule: allow
    port: 80
    proto: tcp
    state: enabled
